# Generated by Django 3.1.6 on 2021-04-16 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hour_sum_diff_srnew',
            name='Month_1',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Месяц_1'),
        ),
        migrations.AlterField(
            model_name='hour_sum_diff_srnew',
            name='Month_10',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Месяц_10'),
        ),
        migrations.AlterField(
            model_name='hour_sum_diff_srnew',
            name='Month_11',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Месяц_11'),
        ),
        migrations.AlterField(
            model_name='hour_sum_diff_srnew',
            name='Month_12',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Месяц_12'),
        ),
        migrations.AlterField(
            model_name='hour_sum_diff_srnew',
            name='Month_2',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Месяц_2'),
        ),
        migrations.AlterField(
            model_name='hour_sum_diff_srnew',
            name='Month_3',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Месяц_3'),
        ),
        migrations.AlterField(
            model_name='hour_sum_diff_srnew',
            name='Month_4',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Месяц_4'),
        ),
        migrations.AlterField(
            model_name='hour_sum_diff_srnew',
            name='Month_5',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Месяц_5'),
        ),
        migrations.AlterField(
            model_name='hour_sum_diff_srnew',
            name='Month_6',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Месяц_6'),
        ),
        migrations.AlterField(
            model_name='hour_sum_diff_srnew',
            name='Month_7',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Месяц_7'),
        ),
        migrations.AlterField(
            model_name='hour_sum_diff_srnew',
            name='Month_8',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Месяц_8'),
        ),
        migrations.AlterField(
            model_name='hour_sum_diff_srnew',
            name='Month_9',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Месяц_9'),
        ),
        migrations.AlterField(
            model_name='hour_sum_straight_srnew',
            name='Month_1',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Месяц_1'),
        ),
        migrations.AlterField(
            model_name='hour_sum_straight_srnew',
            name='Month_10',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Месяц_10'),
        ),
        migrations.AlterField(
            model_name='hour_sum_straight_srnew',
            name='Month_11',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Месяц_11'),
        ),
        migrations.AlterField(
            model_name='hour_sum_straight_srnew',
            name='Month_12',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Месяц_12'),
        ),
        migrations.AlterField(
            model_name='hour_sum_straight_srnew',
            name='Month_2',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Месяц_2'),
        ),
        migrations.AlterField(
            model_name='hour_sum_straight_srnew',
            name='Month_3',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Месяц_3'),
        ),
        migrations.AlterField(
            model_name='hour_sum_straight_srnew',
            name='Month_4',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Месяц_4'),
        ),
        migrations.AlterField(
            model_name='hour_sum_straight_srnew',
            name='Month_5',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Месяц_5'),
        ),
        migrations.AlterField(
            model_name='hour_sum_straight_srnew',
            name='Month_6',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Месяц_6'),
        ),
        migrations.AlterField(
            model_name='hour_sum_straight_srnew',
            name='Month_7',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Месяц_7'),
        ),
        migrations.AlterField(
            model_name='hour_sum_straight_srnew',
            name='Month_8',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Месяц_8'),
        ),
        migrations.AlterField(
            model_name='hour_sum_straight_srnew',
            name='Month_9',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Месяц_9'),
        ),
        migrations.AlterField(
            model_name='hour_sum_sum_srnew',
            name='Month_1',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Месяц_1'),
        ),
        migrations.AlterField(
            model_name='hour_sum_sum_srnew',
            name='Month_10',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Месяц_10'),
        ),
        migrations.AlterField(
            model_name='hour_sum_sum_srnew',
            name='Month_11',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Месяц_11'),
        ),
        migrations.AlterField(
            model_name='hour_sum_sum_srnew',
            name='Month_12',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Месяц_12'),
        ),
        migrations.AlterField(
            model_name='hour_sum_sum_srnew',
            name='Month_2',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Месяц_2'),
        ),
        migrations.AlterField(
            model_name='hour_sum_sum_srnew',
            name='Month_3',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Месяц_3'),
        ),
        migrations.AlterField(
            model_name='hour_sum_sum_srnew',
            name='Month_4',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Месяц_4'),
        ),
        migrations.AlterField(
            model_name='hour_sum_sum_srnew',
            name='Month_5',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Месяц_5'),
        ),
        migrations.AlterField(
            model_name='hour_sum_sum_srnew',
            name='Month_6',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Месяц_6'),
        ),
        migrations.AlterField(
            model_name='hour_sum_sum_srnew',
            name='Month_7',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Месяц_7'),
        ),
        migrations.AlterField(
            model_name='hour_sum_sum_srnew',
            name='Month_8',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Месяц_8'),
        ),
        migrations.AlterField(
            model_name='hour_sum_sum_srnew',
            name='Month_9',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Месяц_9'),
        ),
        migrations.AlterField(
            model_name='mes_sum_diff_srnew',
            name='Month_1',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Месяц_1'),
        ),
        migrations.AlterField(
            model_name='mes_sum_diff_srnew',
            name='Month_10',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Месяц_10'),
        ),
        migrations.AlterField(
            model_name='mes_sum_diff_srnew',
            name='Month_11',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Месяц_11'),
        ),
        migrations.AlterField(
            model_name='mes_sum_diff_srnew',
            name='Month_12',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Месяц_12'),
        ),
        migrations.AlterField(
            model_name='mes_sum_diff_srnew',
            name='Month_2',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Месяц_2'),
        ),
        migrations.AlterField(
            model_name='mes_sum_diff_srnew',
            name='Month_3',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Месяц_3'),
        ),
        migrations.AlterField(
            model_name='mes_sum_diff_srnew',
            name='Month_4',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Месяц_4'),
        ),
        migrations.AlterField(
            model_name='mes_sum_diff_srnew',
            name='Month_5',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Месяц_5'),
        ),
        migrations.AlterField(
            model_name='mes_sum_diff_srnew',
            name='Month_6',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Месяц_6'),
        ),
        migrations.AlterField(
            model_name='mes_sum_diff_srnew',
            name='Month_7',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Месяц_7'),
        ),
        migrations.AlterField(
            model_name='mes_sum_diff_srnew',
            name='Month_8',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Месяц_8'),
        ),
        migrations.AlterField(
            model_name='mes_sum_diff_srnew',
            name='Month_9',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Месяц_9'),
        ),
        migrations.AlterField(
            model_name='mes_sum_straight_srnew',
            name='Month_1',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Месяц_1'),
        ),
        migrations.AlterField(
            model_name='mes_sum_straight_srnew',
            name='Month_10',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Месяц_10'),
        ),
        migrations.AlterField(
            model_name='mes_sum_straight_srnew',
            name='Month_11',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Месяц_11'),
        ),
        migrations.AlterField(
            model_name='mes_sum_straight_srnew',
            name='Month_12',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Месяц_12'),
        ),
        migrations.AlterField(
            model_name='mes_sum_straight_srnew',
            name='Month_2',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Месяц_2'),
        ),
        migrations.AlterField(
            model_name='mes_sum_straight_srnew',
            name='Month_3',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Месяц_3'),
        ),
        migrations.AlterField(
            model_name='mes_sum_straight_srnew',
            name='Month_4',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Месяц_4'),
        ),
        migrations.AlterField(
            model_name='mes_sum_straight_srnew',
            name='Month_5',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Месяц_5'),
        ),
        migrations.AlterField(
            model_name='mes_sum_straight_srnew',
            name='Month_6',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Месяц_6'),
        ),
        migrations.AlterField(
            model_name='mes_sum_straight_srnew',
            name='Month_7',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Месяц_7'),
        ),
        migrations.AlterField(
            model_name='mes_sum_straight_srnew',
            name='Month_8',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Месяц_8'),
        ),
        migrations.AlterField(
            model_name='mes_sum_straight_srnew',
            name='Month_9',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Месяц_9'),
        ),
        migrations.AlterField(
            model_name='mes_sum_sum_srnew',
            name='Month_1',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Месяц_1'),
        ),
        migrations.AlterField(
            model_name='mes_sum_sum_srnew',
            name='Month_10',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Месяц_10'),
        ),
        migrations.AlterField(
            model_name='mes_sum_sum_srnew',
            name='Month_11',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Месяц_11'),
        ),
        migrations.AlterField(
            model_name='mes_sum_sum_srnew',
            name='Month_12',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Месяц_12'),
        ),
        migrations.AlterField(
            model_name='mes_sum_sum_srnew',
            name='Month_2',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Месяц_2'),
        ),
        migrations.AlterField(
            model_name='mes_sum_sum_srnew',
            name='Month_3',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Месяц_3'),
        ),
        migrations.AlterField(
            model_name='mes_sum_sum_srnew',
            name='Month_4',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Месяц_4'),
        ),
        migrations.AlterField(
            model_name='mes_sum_sum_srnew',
            name='Month_5',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Месяц_5'),
        ),
        migrations.AlterField(
            model_name='mes_sum_sum_srnew',
            name='Month_6',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Месяц_6'),
        ),
        migrations.AlterField(
            model_name='mes_sum_sum_srnew',
            name='Month_7',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Месяц_7'),
        ),
        migrations.AlterField(
            model_name='mes_sum_sum_srnew',
            name='Month_8',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Месяц_8'),
        ),
        migrations.AlterField(
            model_name='mes_sum_sum_srnew',
            name='Month_9',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Месяц_9'),
        ),
    ]
