-- MySQL Script generated by MySQL Workbench
-- Fri Mar  5 13:02:25 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema MainData
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema MainData
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `MainData` DEFAULT CHARACTER SET utf8 ;
USE `MainData` ;

-- -----------------------------------------------------
-- Table `MainData`.`Stations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MainData`.`Stations` (
  `IdStation` INT NOT NULL ,
  `NameStation` VARCHAR(50) NOT NULL,
  `Region` VARCHAR(50) NOT NULL,
  `Latitude` FLOAT NOT NULL,
  `Longitude` FLOAT NOT NULL,
  PRIMARY KEY (`IdStation`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MainData`.`Albedo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MainData`.`Albedo` (
  `IdStation` INT NOT NULL,
  `Month_1` FLOAT NOT NULL,
  `Month_2` FLOAT NOT NULL,
  `Month_3` FLOAT NOT NULL,
  `Month_4` FLOAT NOT NULL,
  `Month_5` FLOAT NOT NULL,
  `Month_6` FLOAT NOT NULL,
  `Month_7` FLOAT NOT NULL,
  `Month_8` FLOAT NOT NULL,
  `Month_9` FLOAT NOT NULL,
  `Month_10` FLOAT NOT NULL,
  `Month_11` FLOAT NOT NULL,
  `Month_12` FLOAT NOT NULL,
  INDEX `fk_Albedo_Stations1_idx` (`IdStation` ASC) VISIBLE,
  PRIMARY KEY (`IdStation`),
  CONSTRAINT `fk_Albedo_Stations1`
    FOREIGN KEY (`IdStation`)
    REFERENCES `MainData`.`Stations` (`IdStation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MainData`.`Month`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MainData`.`Month` (
  `idMonth` FLOAT NOT NULL,
  `NameMonth` VARCHAR(45) NULL,
  PRIMARY KEY (`idMonth`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MainData`.`HOUR_Sum_Sum_SR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MainData`.`HOUR_Sum_Sum_SR` (
  `IdStation` INT NOT NULL,
  `idMonth` FLOAT NOT NULL,
  `HOUR_0-1` FLOAT NOT NULL,
  `HOUR_1-2` FLOAT NOT NULL,
  `HOUR_2-3` FLOAT NOT NULL,
  `HOUR_3-4` FLOAT NOT NULL,
  `HOUR_4-5` FLOAT NOT NULL,
  `HOUR_5-6` FLOAT NOT NULL,
  `HOUR_6-7` FLOAT NOT NULL,
  `HOUR_7-8` FLOAT NOT NULL,
  `HOUR_8-9` FLOAT NOT NULL,
  `HOUR_9-10` FLOAT NOT NULL,
  `HOUR_10-11` FLOAT NOT NULL,
  `HOUR_11-12` FLOAT NOT NULL,
  `HOUR_12-13` FLOAT NOT NULL,
  `HOUR_13-14` FLOAT NOT NULL,
  `HOUR_14-15` FLOAT NOT NULL,
  `HOUR_15-16` FLOAT NOT NULL,
  `HOUR_16-17` FLOAT NOT NULL,
  `HOUR_17-18` FLOAT NOT NULL,
  `HOUR_18-19` FLOAT NOT NULL,
  `HOUR_19-20` FLOAT NOT NULL,
  `HOUR_20-21` FLOAT NOT NULL,
  `HOUR_21-22` FLOAT NOT NULL,
  `HOUR_22-23` FLOAT NOT NULL,
  `HOUR_23-24` FLOAT NOT NULL,
  INDEX `fk_HOUR_Sum_Sum_SR_Stations1_idx` (`IdStation` ASC) VISIBLE,
  PRIMARY KEY (`IdStation`, `idMonth`),
  INDEX `fk_HOUR_Sum_Sum_SR_Month1_idx` (`idMonth` ASC) VISIBLE,
  CONSTRAINT `fk_HOUR_Sum_Sum_SR_Stations1`
    FOREIGN KEY (`IdStation`)
    REFERENCES `MainData`.`Stations` (`IdStation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_HOUR_Sum_Sum_SR_Month1`
    FOREIGN KEY (`idMonth`)
    REFERENCES `MainData`.`Month` (`idMonth`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MainData`.`HOUR_Sum_Straight_SR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MainData`.`HOUR_Sum_Straight_SR` (
  `IdStation` INT NOT NULL,
  `idMonth` FLOAT NOT NULL,
  `HOUR_0-1` FLOAT NOT NULL,
  `HOUR_1-2` FLOAT NOT NULL,
  `HOUR_2-3` FLOAT NOT NULL,
  `HOUR_3-4` FLOAT NOT NULL,
  `HOUR_4-5` FLOAT NOT NULL,
  `HOUR_5-6` FLOAT NOT NULL,
  `HOUR_6-7` FLOAT NOT NULL,
  `HOUR_7-8` FLOAT NOT NULL,
  `HOUR_8-9` FLOAT NOT NULL,
  `HOUR_9-10` FLOAT NOT NULL,
  `HOUR_10-11` FLOAT NOT NULL,
  `HOUR_11-12` FLOAT NOT NULL,
  `HOUR_12-13` FLOAT NOT NULL,
  `HOUR_13-14` FLOAT NOT NULL,
  `HOUR_14-15` FLOAT NOT NULL,
  `HOUR_15-16` FLOAT NOT NULL,
  `HOUR_16-17` FLOAT NOT NULL,
  `HOUR_17-18` FLOAT NOT NULL,
  `HOUR_18-19` FLOAT NOT NULL,
  `HOUR_19-20` FLOAT NOT NULL,
  `HOUR_20-21` FLOAT NOT NULL,
  `HOUR_21-22` FLOAT NOT NULL,
  `HOUR_22-23` FLOAT NOT NULL,
  `HOUR_23-24` FLOAT NOT NULL,
  PRIMARY KEY (`IdStation`, `idMonth`),
  INDEX `fk_HOUR_Sum_Straight_SR_Stations1_idx` (`IdStation` ASC) VISIBLE,
  INDEX `fk_HOUR_Sum_Straight_SR_Month1_idx` (`idMonth` ASC) VISIBLE,
  CONSTRAINT `fk_HOUR_Sum_Straight_SR_Stations1`
    FOREIGN KEY (`IdStation`)
    REFERENCES `MainData`.`Stations` (`IdStation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_HOUR_Sum_Straight_SR_Month1`
    FOREIGN KEY (`idMonth`)
    REFERENCES `MainData`.`Month` (`idMonth`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MainData`.`HOUR_Sum_Diff_SR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MainData`.`HOUR_Sum_Diff_SR` (
  `IdStation` INT NOT NULL,
  `idMonth` FLOAT NOT NULL,
  `HOUR_0-1` FLOAT NOT NULL,
  `HOUR_1-2` FLOAT NOT NULL,
  `HOUR_2-3` FLOAT NOT NULL,
  `HOUR_3-4` VARCHAR(45) NOT NULL,
  `HOUR_4-5` FLOAT NOT NULL,
  `HOUR_5-6` FLOAT NOT NULL,
  `HOUR_6-7` FLOAT NOT NULL,
  `HOUR_7-8` FLOAT NOT NULL,
  `HOUR_8-9` FLOAT NOT NULL,
  `HOUR_9-10` FLOAT NOT NULL,
  `HOUR_10-11` FLOAT NOT NULL,
  `HOUR_11-12` FLOAT NOT NULL,
  `HOUR_12-13` FLOAT NOT NULL,
  `HOUR_13-14` FLOAT NOT NULL,
  `HOUR_14-15` FLOAT NOT NULL,
  `HOUR_15-16` FLOAT NOT NULL,
  `HOUR_16-17` FLOAT NOT NULL,
  `HOUR_17-18` FLOAT NOT NULL,
  `HOUR_18-19` FLOAT NOT NULL,
  `HOUR_19-20` FLOAT NOT NULL,
  `HOUR_20-21` FLOAT NOT NULL,
  `HOUR_21-22` FLOAT NOT NULL,
  `HOUR_22-23` FLOAT NOT NULL,
  `HOUR_23-24` FLOAT NOT NULL,
  PRIMARY KEY (`IdStation`, `idMonth`),
  INDEX `fk_HOUR_Sum_Diff_SR_Stations1_idx` (`IdStation` ASC) VISIBLE,
  INDEX `fk_HOUR_Sum_Diff_SR_Month1_idx` (`idMonth` ASC) VISIBLE,
  CONSTRAINT `fk_HOUR_Sum_Diff_SR_Stations1`
    FOREIGN KEY (`IdStation`)
    REFERENCES `MainData`.`Stations` (`IdStation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_HOUR_Sum_Diff_SR_Month1`
    FOREIGN KEY (`idMonth`)
    REFERENCES `MainData`.`Month` (`idMonth`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MainData`.`SUT_Sum_Sum_SR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MainData`.`SUT_Sum_Sum_SR` (
  `IdStation` INT NOT NULL,
  `Month_1` FLOAT NOT NULL,
  `Month_2` FLOAT NOT NULL,
  `Month_3` FLOAT NOT NULL,
  `Month_4` FLOAT NOT NULL,
  `Month_5` FLOAT NOT NULL,
  `Month_6` FLOAT NOT NULL,
  `Month_7` FLOAT NOT NULL,
  `Month_8` FLOAT NOT NULL,
  `Month_9` FLOAT NOT NULL,
  `Month_10` FLOAT NOT NULL,
  `Month_11` FLOAT NOT NULL,
  `Month_12` FLOAT NOT NULL,
  INDEX `fk_SUT_Sum_Sum_SR_Stations_idx` (`IdStation` ASC) VISIBLE,
  PRIMARY KEY (`IdStation`),
  CONSTRAINT `fk_SUT_Sum_Sum_SR_Stations`
    FOREIGN KEY (`IdStation`)
    REFERENCES `MainData`.`Stations` (`IdStation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MainData`.`SUT_Sum_Straight_SR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MainData`.`SUT_Sum_Straight_SR` (
  `IdStation` INT NOT NULL,
  `Month_1` FLOAT NOT NULL,
  `Month_2` FLOAT NOT NULL,
  `Month_3` FLOAT NOT NULL,
  `Month_4` FLOAT NOT NULL,
  `Month_5` FLOAT NOT NULL,
  `Month_6` FLOAT NOT NULL,
  `Month_7` FLOAT NOT NULL,
  `Month_8` FLOAT NOT NULL,
  `Month_9` FLOAT NOT NULL,
  `Month_10` FLOAT NOT NULL,
  `Month_11` FLOAT NOT NULL,
  `Month_12` FLOAT NOT NULL,
  INDEX `fk_SUT_Sum_Straight_SR_Stations1_idx` (`IdStation` ASC) VISIBLE,
  PRIMARY KEY (`IdStation`),
  CONSTRAINT `fk_SUT_Sum_Straight_SR_Stations1`
    FOREIGN KEY (`IdStation`)
    REFERENCES `MainData`.`Stations` (`IdStation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MainData`.`SUT_Sum_Diff_SR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MainData`.`SUT_Sum_Diff_SR` (
  `IdStation` INT NOT NULL,
  `Month_1` FLOAT NOT NULL,
  `Month_2` FLOAT NOT NULL,
  `Month_3` FLOAT NOT NULL,
  `Month_4` FLOAT NOT NULL,
  `Month_5` FLOAT NOT NULL,
  `Month_6` FLOAT NOT NULL,
  `Month_7` FLOAT NOT NULL,
  `Month_8` FLOAT NOT NULL,
  `Month_9` FLOAT NOT NULL,
  `Month_10` FLOAT NOT NULL,
  `Month_11` FLOAT NOT NULL,
  `Month_12` FLOAT NOT NULL,
  INDEX `fk_SUT_Sum_Diff_SR_Stations1_idx` (`IdStation` ASC) VISIBLE,
  PRIMARY KEY (`IdStation`),
  CONSTRAINT `fk_SUT_Sum_Diff_SR_Stations1`
    FOREIGN KEY (`IdStation`)
    REFERENCES `MainData`.`Stations` (`IdStation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
